version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - ./volumes/firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 5000:8080
    depends_on:
      - db
  db:
    image: jsurf/rpi-mariadb    
    hostname: fireflyiiidb
    restart: always
    env_file: .db.env
    volumes:
      - ./volumes/firefly_iii_db:/var/lib/mysql
  fidi: 
    image: fireflyiii/data-importer:latest 
    restart: always 
    env_file: .fidi.env 
    ports:
      - 5050:8080
    depends_on:
      - app
volumes:
   firefly_iii_upload:
   firefly_iii_db:
